import type { SocialPost } from './types';

const avatar = (seed: string) => `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`;

export const samplePosts: SocialPost[] = [
  {
    id: 'post-ana',
    kind: 'image',
    author: 'Ana Santos',
    role: 'Designer',
    department: 'Comunicação',
    avatar: avatar('Ana'),
    time: 'há 2 h',
    body: 'Olha esse registro da nossa aluna do curso de Design. A criatividade dela é simplesmente incrível.',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1400&q=80',
    likes: 56,
    liked: false,
    shares: 5,
    shared: false,
    commentsOpen: false,
    comments: [
      {
        id: 'c1',
        author: 'Lucas Ferreira',
        avatar: avatar('Lucas'),
        body: 'Que demais. Parabéns para ela e para quem acompanhou o processo.',
        time: 'há 1 h',
        likes: 4,
        liked: false,
      },
    ],
  },
  {
    id: 'post-comunicado',
    kind: 'announcement',
    author: 'Única',
    role: 'Comunicação interna',
    department: 'Institucional',
    avatar: avatar('Unica'),
    time: 'há 4 h',
    body: 'Vamos celebrar nossas conquistas e reforçar o que nos faz únicos. Participe das ações e fique por dentro de tudo.',
    bannerTitle: 'Campanha de Endomarketing — Juntos somos mais fortes!',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1400&q=80',
    likes: 32,
    liked: false,
    shares: 8,
    shared: false,
    commentsOpen: false,
    comments: [],
  },
  {
    id: 'post-reconhecimento',
    kind: 'recognition',
    author: 'Helena Duarte',
    role: 'Coordenadora',
    department: 'Coordenação',
    avatar: avatar('Helena'),
    time: 'há 5 h',
    body: 'Obrigado pelo excelente trabalho realizado esta semana. A clareza no atendimento fez diferença para toda a equipe.',
    recognizedName: 'Ana',
    likes: 41,
    liked: true,
    shares: 2,
    shared: false,
    commentsOpen: false,
    comments: [
      {
        id: 'c2',
        author: 'Marina Costa',
        avatar: avatar('Marina'),
        body: 'Merecido. A Ana segurou a fila com muita calma.',
        time: 'há 4 h',
        likes: 2,
        liked: false,
      },
    ],
  },
  {
    id: 'post-lideranca',
    kind: 'leadership',
    author: 'Helena Duarte',
    role: 'Coordenadora',
    department: 'Liderança',
    avatar: avatar('Helena'),
    time: 'há 1 d',
    body: 'Na sexta teremos a reunião geral às 14h, no auditório principal. Levem um ponto que a equipe precisa decidir junta.',
    likes: 18,
    liked: false,
    shares: 3,
    shared: false,
    commentsOpen: false,
    comments: [],
  },
  {
    id: 'post-enquete',
    kind: 'poll',
    author: 'João Ferreira',
    role: 'Analista acadêmico',
    department: 'Secretaria',
    avatar: avatar('Joao'),
    time: 'há 6 h',
    body: 'Qual horário funciona melhor para a próxima reunião de equipe?',
    likes: 9,
    liked: false,
    shares: 1,
    shared: false,
    votedId: null,
    poll: [
      { id: 'p1', label: '09h', votes: 4 },
      { id: 'p2', label: '14h', votes: 11 },
      { id: 'p3', label: '16h', votes: 6 },
    ],
    commentsOpen: false,
    comments: [],
  },
  {
    id: 'post-evento',
    kind: 'event',
    author: 'Lívia Ramos',
    role: 'Designer',
    department: 'Comunicação',
    avatar: avatar('Livia'),
    time: 'há 8 h',
    body: 'Treinamento de produto para quem entrou neste semestre. As vagas são limitadas.',
    eventWhen: '17 de outubro · 14:00 – 16:00',
    eventWhere: 'Sala 2 · Bloco acadêmico',
    likes: 14,
    liked: false,
    shares: 4,
    shared: false,
    commentsOpen: false,
    comments: [],
  },
  {
    id: 'post-texto',
    kind: 'text',
    author: 'Matheus Larrie',
    role: 'Colaborador',
    department: 'Comunicação',
    avatar: avatar('Matheus'),
    time: 'há 3 h',
    body: 'Hoje foi um dia de muito aprendizado. Orgulho de fazer parte desta equipe.',
    likes: 22,
    liked: false,
    shares: 0,
    shared: false,
    commentsOpen: false,
    comments: [],
  },
];
